import { NonTechnicalCertificate } from "@/types/certificate";

export const nonTechnicalCertificates: NonTechnicalCertificate[] = [
  {
    id: "iaeng-membership",
    title: "IAENG Membership Certificate",
    organization: "IAENG (International Association of Engineers)",
    role: "Member",
    issueDate: "Apr 2023",
    location: "International",
    image: "/certificates/IAENG.webp",
    skills: ["Scientific Research", "Engineering", "Technology Innovation", "Professional Development"],
    slug: "iaeng-membership",
    description: "Member of the International Association of Engineers, participating in scientific and engineering research, and contributing to technology advancement discussions.",
  },
  {
    id: "msdhs-volunteer",
    title: "International Volunteer Day 2023",
    organization: "Ministry of Social Development and Human Security of Thailand (MSDHS)",
    role: "Accelerator",
    issueDate: "Nov 2023",
    location: "Thailand",
    image: "/certificates/MSDHS.webp",
    skills: ["Community Development", "Sustainable Development", "Public Engagement", "Social Impact"],
    slug: "msdhs-volunteer",
    description: "Participated in International Volunteer Day 2023 with the theme 'If Everyone Did...', contributing to achieving Sustainable Development Goals (SDGs) through volunteerism and supporting public participation in development processes.",
  },
  {
    id: "undp-kenya-volunteer",
    title: "UNDP Kenya Volunteer Certificate",
    organization: "UNDP Kenya",
    role: "AI Digital Skills Volunteer",
    issueDate: "Dec 2024",
    location: "Kenya · Remote",
    image: "/certificates/UNDP_Kenya.webp",
    skills: ["AI Technology", "Digital Skills Training", "Public Sector Development", "Innovation Management"],
    slug: "undp-kenya-volunteer",
    description: "Worked on raising awareness about AI programs by UNDP, contributing to the Africa Centre of Competence for Digital & AI Skilling initiative, collaborating with Microsoft EA and KSG Kenya to equip public servants with essential digital skills.",
  },
  {
    id: "aae-awareness-lead",
    title: "Awareness Lead Certificate",
    organization: "African Association of Entrepreneurs (AAE)",
    role: "Awareness Lead",
    issueDate: "Aug 2024",
    location: "Africa · Remote",
    image: "/certificates/Awareness_lead.webp",
    skills: ["Leadership", "Report Writing", "Business Analysis", "Team Collaboration"],
    slug: "aae-awareness-lead",
    description: "Generated comprehensive reports on entrepreneurship environments in Africa over 12 weeks, collaborating with a team of 12 writers for annual publication, analyzing SME operations across different African countries.",
  },
  {
    id: "aae-publication-lead",
    title: "Publication Lead Certificate",
    organization: "African Association of Entrepreneurs (AAE)",
    role: "Publication Lead",
    issueDate: "May 2024",
    location: "Africa · Remote",
    image: "/certificates/Publication lead.webp",
    skills: ["Publication Management", "Team Leadership", "Content Strategy", "Stakeholder Management"],
    slug: "aae-publication-lead",
    description: "Led volunteer recruitment and article writing process, managed publication of business environment articles, and coordinated with writers for the annual report, creating a virtual space for SME showcase.",
  },
  {
    id: "aae-awareness-volunteer",
    title: "Awareness Volunteer Certificate",
    organization: "African Association of Entrepreneurs (AAE)",
    role: "Awareness Volunteer",
    issueDate: "Aug 2024",
    location: "Africa · Remote",
    image: "/certificates/Awareness_volunteer.webp",
    skills: ["Community Engagement", "Social Media", "Content Creation", "Event Promotion"],
    slug: "aae-awareness-volunteer",
    description: "Supported awareness initiatives for African entrepreneurship, contributed to promotional activities, and assisted in community engagement efforts, increasing visibility of AAE programs and enhancing community awareness.",
  },
];
