import { TechnicalCertificate } from "@/types/certificate";

export const technicalCertificates: TechnicalCertificate[] = [
  {
    id: "aws-genai-foundations",
    title: "AWS Academy Graduate - Generative AI Foundations",
    issuer: "Amazon Web Services (AWS)",
    issueDate: "Jan 2026",
    skills: ["Generative AI", "AWS", "Machine Learning"],
    image: "/certificates/AWS Academy Graduate - Generative AI Foundations .webp",
    badgeImage: "/certificates/aws-academy-graduate-generative-ai-foundations-badge.webp",
    category: "AI/ML",
    slug: "aws-genai-foundations",
  },
  {
    id: "azure-ai-engineer",
    title: "Microsoft Certified: Azure AI Engineer Associate",
    issuer: "Microsoft",
    issueDate: "Dec 2025",
    expiryDate: "Dec 2026",
    credentialId: "6EBE3160733F7B87",
    credentialUrl: "https://learn.microsoft.com/api/credentials/share/en-us/HiteshKumar-5704/6EBE3160733F7B87",
    skills: ["Azure", "AI Engineering", "Machine Learning", "Generative AI"],
    image: "/certificates/Microsoft Certified Azure AI Engineer Associate.webp",
    badgeImage: "/certificates/Badge Microsoft Certified Azure AI Engineer Associate.webp",
    category: "Cloud",
    slug: "azure-ai-engineer",
  },
  {
    id: "salesforce-agentforce",
    title: "Salesforce Certified Agentforce Specialist",
    issuer: "Salesforce",
    issueDate: "Dec 2025",
    expiryDate: "Dec 2029",
    skills: ["Salesforce", "Agentforce", "AI Agents", "CRM"],
    image: "/certificates/Salesforce Certified Agentforce Specialist.webp",
    badgeImage: "/certificates/Certificate 1 Salesforce Certified Agentforce Specialist.webp",
    category: "AI/ML",
    slug: "salesforce-agentforce",
  },
  {
    id: "self-driving-cars",
    title: "Self-Driving Cars Specialization",
    issuer: "University of Toronto",
    issueDate: "Nov 2025",
    credentialId: "JIGFG5VDHBMS",
    credentialUrl: "https://www.coursera.org/account/accomplishments/specialization/JIGFG5VDHBMS",
    skills: ["Autonomous Vehicles", "Computer Vision", "Deep Learning", "Sensor Fusion"],
    image: "/certificates/Self-Driving Cars.webp",
    category: "AI/ML",
    slug: "self-driving-cars",
  },
  {
    id: "azure-fundamentals",
    title: "Microsoft Certified: Azure Fundamentals",
    issuer: "Microsoft",
    issueDate: "Jun 2025",
    credentialId: "FFA474E81734A1CC",
    credentialUrl: "https://learn.microsoft.com/api/credentials/share/en-us/HiteshKumar-5704/FFA474E81734A1CC",
    skills: ["Azure", "Cloud Concepts", "Azure Core Services", "Azure Governance"],
    image: "/certificates/Report Microsoft Certified Azure Fundamentals.webp",
    badgeImage: "/certificates/Microsoft Certified Azure Fundamentals.webp",
    category: "Cloud",
    slug: "azure-fundamentals",
  },
  {
    id: "ccict-2025",
    title: "Certificate of Appreciation – CCICT 2025",
    issuer: "B.M. Institute Of Engineering & Technology (BMIET)",
    issueDate: "Apr 2025",
    skills: ["Artificial Intelligence", "Computational Intelligence", "Research"],
    image: "/certificates/Certificate of Appreciation – CCICT 2025.webp",
    category: "AI/ML",
    slug: "ccict-2025",
  },
  {
    id: "genai-data-analysis",
    title: "Introduction to Generative AI for Data Analysis",
    issuer: "Microsoft",
    issueDate: "Feb 2025",
    credentialId: "L3E3YXJKUV23",
    credentialUrl: "https://learn.microsoft.com/api/credentials/share/en-us/HiteshKumar-5704/L3E3YXJKUV23",
    skills: ["Generative AI", "Data Analysis", "AI Tools"],
    image: "/certificates/Introduction to Generative AI for Data Analysis.webp",
    category: "Data",
    slug: "genai-data-analysis",
  },
  {
    id: "5g-fundamentals",
    title: "5G Network Fundamentals",
    issuer: "Institut Mines-Télécom (IMT)",
    issueDate: "Jan 2025",
    credentialId: "B3VU4DJH7V8D",
    credentialUrl: "https://www.coursera.org/account/accomplishments/B3VU4DJH7V8D",
    skills: ["5G Networks", "Telecommunications", "Network Architecture"],
    image: "/certificates/5G Network Fundamentals.webp",
    category: "Other",
    slug: "5g-fundamentals",
  },
  {
    id: "salesforce-ai-specialist",
    title: "Salesforce Certified AI Specialist",
    issuer: "Salesforce",
    issueDate: "Dec 2024",
    expiryDate: "Dec 2028",
    credentialUrl: "https://www.salesforce.com/trailblazer/",
    skills: ["Salesforce", "Generative AI", "AI Implementation"],
    image: "/certificates/Salesforce Certified AI Specialist.webp",
    badgeImage: "/certificates/Salesforce Certified AI Specialist.webp",
    category: "AI/ML",
    slug: "salesforce-ai-specialist",
  },
  {
    id: "ibm-ai-getting-started",
    title: "Getting Started with Artificial Intelligence",
    issuer: "IBM",
    issueDate: "Aug 2024",
    skills: ["Artificial Intelligence", "Machine Learning", "AI Fundamentals"],
    image: "/certificates/Getting Started with Artificial Intelligence.webp",
    category: "AI/ML",
    slug: "ibm-ai-getting-started",
  },
  {
    id: "github-foundations",
    title: "GitHub Foundations",
    issuer: "GitHub",
    issueDate: "Nov 2024",
    expiryDate: "Nov 2027",
    skills: ["GitHub", "Git", "Version Control", "Development"],
    image: "/certificates/GitHub Foundations.webp",
    category: "Web Development",
    slug: "github-foundations",
  },
  {
    id: "isro-rs-gis",
    title: "RS and GIS Management / Automated Feature Extraction",
    issuer: "Indian Space Research Organisation (ISRO)",
    issueDate: "Nov 2023",
    skills: ["Remote Sensing", "GIS", "Feature Extraction", "Geospatial Analysis"],
    image: "/certificates/1 RS and GIS Management Automated Feature Extraction from High Resolution Images.webp",
    category: "Data",
    slug: "isro-rs-gis",
  },
  {
    id: "ni-aiml-workshop",
    title: "Workshop on AI/ML",
    issuer: "NI (National Instruments)",
    issueDate: "May 2023",
    skills: ["Artificial Intelligence", "Machine Learning", "LabVIEW"],
    image: "/certificates/Workshop on AIML.webp",
    category: "AI/ML",
    slug: "ni-aiml-workshop",
  },
  {
    id: "nvidia-gtc",
    title: "NVIDIA GTC 2023",
    issuer: "NVIDIA",
    issueDate: "Mar 2023",
    skills: ["CUDA", "GPU Computing", "AI Acceleration"],
    image: "/certificates/NvdiaGTC.webp",
    category: "AI/ML",
    slug: "nvidia-gtc",
  },
  {
    id: "snap-ar-hackathon",
    title: "SnapAR Hackathon Winner",
    issuer: "Snap Inc.",
    issueDate: "May 2023",
    skills: ["AR", "VR", "Lens Studio", "Mobile Development"],
    image: "/certificates/SnapAR Hackathon.webp",
    category: "Web Development",
    slug: "snap-ar-hackathon",
  },
  {
    id: "devtown-web-bootcamp",
    title: "Bootcamp for Web Development",
    issuer: "DevTown",
    issueDate: "Sep 2022",
    skills: ["Web Development", "Frontend", "Backend", "Full Stack"],
    image: "/certificates/DevTown.webp",
    category: "Web Development",
    slug: "devtown-web-bootcamp",
  },
  {
    id: "ibm-spss-analytics",
    title: "Predictive Analytics using IBM SPSS Modeler - Advanced",
    issuer: "IBM",
    issueDate: "Nov 2024",
    credentialId: "df367e4830954b729a83103387e3d315",
    credentialUrl: "https://www.coursera.org/account/accomplishments/df367e4830954b729a83103387e3d315",
    skills: ["Predictive Analytics", "SPSS", "Data Science", "Machine Learning"],
    image: "/certificates/Predictive Analytics using IBM SPSS Modeler.webp",
    category: "Data",
    slug: "ibm-spss-analytics",
  },
  {
    id: "postman-api-fundamentals",
    title: "Postman API Fundamentals Student Expert",
    issuer: "Postman",
    issueDate: "Nov 2024",
    credentialId: "672a660a58b626319e1256fb",
    credentialUrl: "https://www.postman.com/badges/api-expertise/672a660a58b626319e1256fb",
    skills: ["API Development", "REST APIs", "Postman", "API Testing"],
    image: "/certificates/Postman API Fundamentals Student Expert.webp",
    category: "Web Development",
    slug: "postman-api-fundamentals",
  },
  {
    id: "chandigarh-ai-models",
    title: "Advanced Credit Program - AI Models",
    issuer: "Chandigarh University",
    issueDate: "Oct 2024",
    skills: ["AI Models", "Deep Learning", "Neural Networks", "Generative AI"],
    image: "/certificates/1AI Models Advanced credit program.webp",
    badgeImage: "/certificates/2AI Models Advanced credit program.webp",
    category: "AI/ML",
    slug: "chandigarh-ai-models",
  },
  {
    id: "salesforce-ai-associate",
    title: "Salesforce Certified AI Associate",
    issuer: "Salesforce",
    issueDate: "Oct 2024",
    expiryDate: "Dec 2027",
    credentialUrl: "https://www.salesforce.com/trailblazer/",
    skills: ["Salesforce", "AI/ML", "Generative AI", "CRM"],
    image: "/certificates/Salesforce Certified AI Associate.webp",
    badgeImage: "/certificates/1Salesforce Certified AI Associate.webp",
    category: "AI/ML",
    slug: "salesforce-ai-associate",
  },
  {
    id: "intel-ai-global-impact",
    title: "Intel AI Global Impact Festival 2024",
    issuer: "Intel Corporation",
    issueDate: "Oct 2024",
    skills: ["AI/ML", "OpenVINO", "Edge AI", "Intel Technologies"],
    image: "/certificates/1Intel AI Global Impact Festival 2024.webp",
    badgeImage: "/certificates/2Intel AI Global Impact Festival 2024.webp",
    category: "AI/ML",
    slug: "intel-ai-global-impact",
  },
  {
    id: "datacamp-data-analyst",
    title: "Data Analyst Associate",
    issuer: "DataCamp",
    issueDate: "Oct 2024",
    expiryDate: "Oct 2026",
    credentialId: "DAA0011328888719",
    credentialUrl: "https://www.datacamp.com/certificate/DAA0011328888719",
    skills: ["Data Analysis", "SQL", "Data Visualization", "Statistics"],
    image: "/certificates/Data Analyst Associate.webp",
    category: "Data",
    slug: "datacamp-data-analyst",
  },
  {
    id: "scrum-foundation",
    title: "Scrum Foundation Professional Certification (SFPC)",
    issuer: "Certiprof",
    issueDate: "Oct 2024",
    expiryDate: "Oct 2027",
    skills: ["Scrum", "Agile", "Project Management", "Team Leadership"],
    image: "/certificates/Scrum Foundation Professional Certification - SFPC.webp",
    category: "Other",
    slug: "scrum-foundation",
  },
  {
    id: "chandigarh-acp-2024",
    title: "Advanced Credit Program - Python",
    issuer: "Chandigarh University",
    issueDate: "Sep 2024",
    skills: ["Python", "Programming", "Data Structures", "Algorithms"],
    image: "/certificates/Advanced Credit Program-2024.webp",
    badgeImage: "/certificates/1Advanced Credit Program-2024.webp",
    category: "Web Development",
    slug: "chandigarh-acp-python",
  },
  {
    id: "freecodecamp-ml-python",
    title: "Machine Learning with Python",
    issuer: "freeCodeCamp",
    issueDate: "Sep 2024",
    credentialId: "hitesh_aiml-mlwp",
    credentialUrl: "https://freecodecamp.org/hitesh_aiml-mlwp",
    skills: ["Machine Learning", "Python", "Scikit-learn", "TensorFlow"],
    image: "/certificates/free-code-camp.webp",
    category: "AI/ML",
    slug: "freecodecamp-ml-python",
  },
  {
    id: "coursera-applied-ml-python",
    title: "Applied Machine Learning in Python",
    issuer: "Coursera (University of Michigan)",
    issueDate: "Sep 2024",
    expiryDate: "Sep 2026",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/APPLIED-ML-PYTHON",
    skills: ["Machine Learning", "Python", "Scikit-learn", "Supervised Learning"],
    image: "/certificates/Applied Machine Learning in Python (University of Michigan).webp",
    category: "AI/ML",
    slug: "coursera-applied-ml-python",
  },
  {
    id: "oracle-cloud-data-management",
    title: "Oracle Cloud Data Management Foundation Associate",
    issuer: "Oracle",
    issueDate: "Aug 2024",
    expiryDate: "Aug 2024",
    credentialId: "OC5149110",
    credentialUrl: "https://www.oracle.com/credentials/",
    skills: ["Oracle Cloud", "Data Management", "Database", "Cloud Infrastructure"],
    image: "/certificates/Oracle Cloud Data Management foundation associate-1.webp",
    badgeImage: "/certificates/Oracle Cloud Data Management foundation associate-2.webp",
    category: "Cloud",
    slug: "oracle-cloud-data-management",
  },
  {
    id: "aviatrix-multicloud",
    title: "Multicloud Network Associate",
    issuer: "Aviatrix",
    issueDate: "Sep 2024",
    expiryDate: "Sep 2027",
    skills: ["Cloud Networking", "Multicloud", "Network Security", "Aviatrix"],
    image: "/certificates/Multicloud Network Associate.webp",
    category: "Cloud",
    slug: "aviatrix-multicloud",
  },
  {
    id: "databricks-genai",
    title: "Academy Accreditation - Generative AI Fundamentals",
    issuer: "Databricks",
    issueDate: "Aug 2024",
    expiryDate: "Aug 2026",
    credentialId: "113317956",
    credentialUrl: "https://databricks.com/learn/certification",
    skills: ["Generative AI", "LLMs", "Databricks", "Data Engineering"],
    image: "/certificates/Academy Accreditation - Generative AI Fundamentals.webp",
    category: "AI/ML",
    slug: "databricks-genai",
  },
  {
    id: "ibm-data-science-intro",
    title: "What is Data Science?",
    issuer: "IBM",
    issueDate: "Oct 2023",
    skills: ["Data Science", "Analytics", "Big Data", "Python"],
    image: "/certificates/What_is_Data_Science.webp",
    category: "Data",
    slug: "ibm-data-science-intro",
  },
  {
    id: "tata-data-visualization",
    title: "Data Visualisation: Empowering Business with Effective Insights",
    issuer: "Tata Group",
    issueDate: "Jul 2024",
    credentialId: "BGNnseW5aRunsadjD",
    credentialUrl: "https://www.coursera.org/account/accomplishments/BGNnseW5aRunsadjD",
    skills: ["Data Visualization", "Business Intelligence", "Tableau", "Analytics"],
    image: "/certificates/Data Visualisation Empowering Business with Effective Insights.webp",
    category: "Data",
    slug: "tata-data-visualization",
  },
  {
    id: "oracle-oci-genai",
    title: "Oracle Cloud Infrastructure 2024 Generative AI Certified Professional",
    issuer: "Oracle",
    issueDate: "Jul 2024",
    credentialId: "100735643OCI2024GAIOCP",
    credentialUrl: "https://www.oracle.com/credentials/",
    skills: ["Generative AI", "Oracle Cloud", "LLMs", "Cloud AI Services", "Machine Learning"],
    image: "/certificates/Oracle Cloud Infrastructure 2024 Generative Al Certified Professional.webp",
    category: "Cloud",
    slug: "oracle-oci-genai",
  },
  {
    id: "azure-ai-fundamentals",
    title: "AI-900: Microsoft Azure AI Fundamentals",
    issuer: "Microsoft",
    issueDate: "Jun 2024",
    credentialId: "90046070",
    credentialUrl: "https://learn.microsoft.com/api/credentials/share/en-us/HiteshKumar-5704/90046070",
    skills: ["Azure AI", "Generative AI", "Machine Learning", "AI Fundamentals"],
    image: "/certificates/AI-900 Microsoft Azure AI Fundamentals.webp",
    category: "AI/ML",
    slug: "azure-ai-fundamentals",
  },
  {
    id: "startup-india",
    title: "StartUp India Learning Program",
    issuer: "Invest India",
    issueDate: "Oct 2023",
    credentialId: "85164848",
    credentialUrl: "https://www.startupindia.gov.in/",
    skills: ["Entrepreneurship", "Business Development", "Startup Ecosystem", "Innovation"],
    image: "/certificates/StartUp India Learning Program.webp",
    category: "Other",
    slug: "startup-india",
  },
  {
    id: "coursera-data-science-orientation",
    title: "Data Science Orientation",
    issuer: "Coursera",
    issueDate: "Oct 2023",
    skills: ["Data Science", "Data Analysis", "Statistics", "Python"],
    image: "/certificates/Data Science Orientation.webp",
    category: "Data",
    slug: "coursera-data-science-orientation",
  },
];
